config/routes.rb
Rails.application.routes.draw do

  root :to => 'index#index'

  resources :index

  resources :toyotas, :except => [:new, :edit, :create, :update, :destroy] do
    resources :toyota_models
  end

  resources :subarus, :except => [:new, :edit, :create, :update, :destroy]  do
    resources :subaru_models
  end

end

app/models/subaru.rb
class Subaru < ActiveRecord::Base
  has_many :subaru_models
end

app/models/subaru_model.rb
class SubaruModel < ActiveRecord::Base
  belongs_to :subaru
  validates_presence_of :name, :year
end

app/models/toyota.rb
class Toyota < ActiveRecord::Base
  has_many :toyota_models
end

app/models/toyota_model.rb
class ToyotaModel < ActiveRecord::Base
  belongs_to :toyota
  validates_presence_of :name, :year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @toyotas = Toyota.all
    @subarus = Subaru.all
  end
end

app/controllers/subaru_models_controller.rb
class SubaruModelsController < ApplicationController
  def index
    @subaru_models = SubaruModel.all
  end
end

app/controllers/subarus_controller.rb
class SubarusController < ApplicationController
  def index
    @subarus = Subaru.all
  end
end

app/controllers/toyota_models_controller.rb
class ToyotaModelsController < ApplicationController
  def index
    @toyota_models = ToyotaModel.all
  end
end

app/controllers/toyotas_controller.rb
class ToyotasController < ApplicationController
  def index
    @toyota = Toyota.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/index.html.erb
<div class="row row-centered">
  <div class="col-md-6 col-centered">
    <button type="button" class="btn btn-lg btn-custom-toyota"><%= link_to "Toyota", toyota_toyota_models_path(toyota) %></button>
    <button type="button" class="btn btn-lg btn-custom-toyota"><%= link_to "Subaru", subaru_subaru_models_path %></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AccessoryApp</title>
  <meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'shared/navbar' %>
    <%= yield %>

  </div>
</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Toyota | Subaru of Corvallis</a>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Admin" %></li>
  </ul>
</nav>

app/views/toyota_models/index.html.erb
<h1>Pick your Toyota Model</h1>